<?php
/**
 * @file
 * Main file for custom hooks and functions.
 */

use \Drupal\imagemagick\ImagemagickExecArguments;
use \Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_theme().
 */
function blog_theme($existing, $type, $theme, $path) {
  return [
    'blog_previous_next' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => 'blog.theme.inc',
      'pattern' => 'blog_previous_next__'
    ],
    'blog_social_share' => [
      'variables' => [
        'url' => NULL,
        'label' => NULL,
      ],
      'file' => 'blog.theme.inc',
    ],
    'blog_label_with_icon_media_formatter' => [
      'variables' => [
        'url' => NULL,
        'label' => NULL,
        'filesize' => NULL,
        'media_type' => NULL,
        'mime_type' => NULL,
      ],
      'file' => 'blog.theme.inc',
    ],
  ];
}

/**
 * Implements hook_imagemagick_arguments_alter().
 */
function blog_imagemagick_arguments_alter(ImagemagickExecArguments $arguments, $command) {
  $arguments->add('-sampling-factor 4:2:0');
  $arguments->add('-interlace Plane');
  $arguments->add('-strip');
}

/**
 * Implements hook_query_TAG_alter().
 */
function blog_query_entity_query_random_alter(AlterableInterface $query) {
  $query->orderRandom();
}